"""update Product(unique name)

Revision ID: 91c428cb3f75
Revises: 811d689b132a
Create Date: 2026-02-13 18:39:51.541981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91c428cb3f75'
down_revision: Union[str, Sequence[str], None] = '811d689b132a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_products_name', 'products', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_products_name', 'products', type_='unique')
    # ### end Alembic commands ###
